version: '3.8'

services:
  # Service 1
  db:
    image: postgres:14-alpine
    container_name: fx-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fx_warehouse
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Service 2: The Spring Boot Application
  app:
    build: .
    container_name: fx-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fx_warehouse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
volumes:
  postgres-data: